name: Setup Avira and Get ID on Windows VM

on:
  workflow_dispatch:

jobs:
  setup_avira:
    runs-on: windows-latest
    steps:
      - name: Create User
        run: |
          net user Nik6348 Shiv@Shakti143 /add

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install Python and required packages
        run: |
          choco install -y python3 pip
          pip install pyautogui requests telegraph

      - name: Download and Install Avira
        run: |
          # Download Avira installer
          curl -s -L -o Avica_setup.exe "https://download.avica.link/downloader/Avica_setup.exe"

          # Silently install Avira
          .\Avica_setup.exe /S

      - name: Execute Python script
        run: |
          python -c "import pyautogui as pag; pag.click(897, 64, duration=2)"
          python -c "import pyautogui as pag; import time; import requests; import os; actions = [(516, 405, 4), (50, 100, 1), (249, 203, 4), (249, 203, 4), (249, 203, 4), (249, 203, 4), (447, 286, 4)]; time.sleep(10); img_filename = 'AvicaRemoteID.png'; def upload_image_to_gofile(img_filename): url = 'https://store1.gofile.io/uploadFile'; try: with open(img_filename, 'rb') as img_file: files = {'file': img_file}; response = requests.post(url, files=files); response.raise_for_status(); result = response.json(); if result['status'] == 'ok': download_page = result['data']['downloadPage']; with open('show.bat', 'a') as bat_file: bat_file.write(f'\necho Avica Remote ID : {download_page}'); return download_page; else: print('Upload error:', result.get('status')); return None; except Exception as e: print(f'Failed to upload image: {e}'); return None; for x, y, duration in actions: pag.click(x, y, duration=duration); if (x, y) == (249, 203): time.sleep(1); pag.click(x, y, duration=duration); if (x, y) == (447, 286): os.system('\"C:\\Program Files x86\\Avica\\Avica.exe\"'); time.sleep(5); pag.click(249, 203, duration=4); time.sleep(10); pag.screenshot().save(img_filename); gofile_link = upload_image_to_gofile(img_filename); if gofile_link: print(f'Image uploaded successfully. Link: {gofile_link}'); else: print('Failed to upload the image.'); time.sleep(10); print('Done!')"

      - name: Display Avira ID and credentials
        run: |
          type show.bat
          echo Username: Nik6348
          echo Password: Shiv@S
          hakti143
